In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np

In [9]:
# Zeroes
a = np.zeros((2, 5)) # a = np.zeros([2, 5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# Ones
b = np.ones((3, 5), dtype = "float16")
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float16)

In [12]:
# Specific Number
c = np.full((2, 2), 22)
c

array([[22, 22],
       [22, 22]])

In [14]:
# Like another
d = np.full_like(c, 32)
d

array([[32, 32],
       [32, 32]])

In [19]:
# Random!
e = np.random.rand(3, 5)
e

array([[0.26071169, 0.54089208, 0.16335181, 0.08331191, 0.87986192],
       [0.03423243, 0.17580475, 0.24824994, 0.82487262, 0.90335496],
       [0.87343427, 0.25266033, 0.80245454, 0.44674717, 0.07404425]])

In [24]:
# Random Integers (min value, max value, size)
f = np.random.randint(4, 15, size = (7, 2))
f

array([[13, 10],
       [12, 12],
       [11, 13],
       [11, 13],
       [ 4, 14],
       [10, 10],
       [ 7,  7]])

In [32]:
# Repeat an array
g = np.array([[1, 2, 3]])
h = np.repeat(g, 5, axis = 0)
h

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [44]:
# Problem Build an n-dimensional array of specified value.

a = np.ones((5,5), dtype = "int8")
a
a[1:-1, 1:-1] = 0
a
a[2, 2] = 9
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [46]:
# Full Copy

a = np.array([1,2,3])
a
b = a.copy()
b[2] = 22
a
b

array([1, 2, 3])

array([1, 2, 3])

array([ 1,  2, 22])