In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np

In [14]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [10, 11, 12, 13, 14, 15, 16]])
a

# Get element [r,c]
a[0, 3]
a[1, -1]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15, 16]])

4

16

In [7]:
# Access Row and Columns - Using ':'
a[:, 1]
a[0, :]

array([ 2, 11])

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Start Index: End Index: Step Size - Access
a[1:6:2]

# Updating
a[0, 3] = 121
a[:, 5] = 0
a

array([[10, 11, 12, 13, 14, 15, 16]])

array([[  1,   2,   3, 121,   5,   0,   7],
       [ 10,  11,  12,  13,  14,   0,  16]])

In [21]:
# 3-D Example

b = np.array([[[1, 2], [3, 4]],[[5, 6],[7, 8]]])
b

b[:, 1, 0]
b[:, 1, :]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

array([3, 7])

array([[3, 4],
       [7, 8]])

In [22]:
# Update
b[:, 1, :] = [[4, 4],[0, 0]]
b

array([[[1, 2],
        [4, 4]],

       [[5, 6],
        [0, 0]]])