In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np

In [3]:
# Reorganization

before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before

after = before.reshape((8, 1))
after

after_two = before.reshape((4, 2))
after_two

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
# Vertical Stacking

v1 = np.array([1, 2, 3, 4])
v2 = np.array([2, 4, 6, 8])

np.vstack([v1, v2, v1, v1])

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [7]:
# Horizontal Stacking

h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

h1
h2

np.hstack((h1, h2))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[0., 0.],
       [0., 0.]])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [13]:
# Generate Random numbers and storing in an Array

from random import randint

for _ in range(4):
    print(",".join([str(randint(0, 10)) for _ in range(20)]))
    
# Copy below to data.txt

9,1,3,0,5,4,2,0,6,3,2,2,4,6,4,3,2,7,0,2
1,7,6,3,4,0,1,7,2,7,3,1,3,2,2,5,10,4,9,8
9,3,3,9,9,2,2,6,8,6,7,6,5,1,7,4,7,9,8,0
2,2,10,0,0,5,7,6,9,10,10,3,7,9,3,5,3,0,8,3


In [14]:
# Load Data from File

filedata = np.genfromtxt("data.txt", delimiter = ',')
filedata = filedata.astype("int32")
filedata

array([[ 9,  1,  3,  0,  5,  4,  2,  0,  6,  3,  2,  2,  4,  6,  4,  3,
         2,  7,  0,  2],
       [ 1,  7,  6,  3,  4,  0,  1,  7,  2,  7,  3,  1,  3,  2,  2,  5,
        10,  4,  9,  8],
       [ 9,  3,  3,  9,  9,  2,  2,  6,  8,  6,  7,  6,  5,  1,  7,  4,
         7,  9,  8,  0],
       [ 2,  2, 10,  0,  0,  5,  7,  6,  9, 10, 10,  3,  7,  9,  3,  5,
         3,  0,  8,  3]], dtype=int32)

In [16]:
# Advanced Indexing & Boolean Masking

filedata > 5

array([[ True, False, False, False, False, False, False, False,  True,
        False, False, False, False,  True, False, False, False,  True,
        False, False],
       [False,  True,  True, False, False, False, False,  True, False,
         True, False, False, False, False, False, False,  True, False,
         True,  True],
       [ True, False, False,  True,  True, False, False,  True,  True,
         True,  True,  True, False, False,  True, False,  True,  True,
         True, False],
       [False, False,  True, False, False, False,  True,  True,  True,
         True,  True, False,  True,  True, False, False, False, False,
         True, False]])

In [17]:
filedata[filedata > 5]

array([ 9,  6,  6,  7,  7,  6,  7,  7, 10,  9,  8,  9,  9,  9,  6,  8,  6,
        7,  6,  7,  7,  9,  8, 10,  7,  6,  9, 10, 10,  7,  9,  8],
      dtype=int32)

In [21]:
np.any(filedata > 5, axis = 0)

np.all(filedata > 2, axis = 0)

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True])

array([False, False,  True, False, False, False, False, False, False,
        True, False, False,  True, False, False,  True, False, False,
       False, False])